export const ShopTypesData = {
    FETCHING_START_ASYNC_START : 'FETCHING_START_ASYNC_START',
    FETSHING_START_ASYNC_SUCCESS : 'FETSHING_START_ASYNC_SUCCESS',
    FETSHING_START_ASYNC_FAILURE : 'FETSHING_START_ASYNC_FAILURE'
}