export const CartTypesFood = {
    ADD_MORE_QUANTITY : 'ADD_MORE_QUANTITY',
    PLUS_ONE_QUANTITY : 'PLUS_ONE_QUANTITY',
    REMOVE_MORE_QUANTITY : 'REMOVE_MORE_QUANTITY',
    TOGGLE_HIDDEN_PAGE : 'TOGGLE_HIDDEN_PAGE'
}